server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

logging:
  level:
    '[com.example.demo]': INFO
    '[org.hibernate.type]': TRACE