version: '3'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: metadb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - mysql_repo:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - test_network
  application:
    build: .
    restart: always
    ports:
      - 80:8080 
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/metadb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - test_network
networks:                                                                                                                                                                                                       
  test_network:
volumes:
  mysql_repo:

